#!/usr/bin/env zsh

# format
# zpm load @plugin-type/user/plugin-name
# example 

zpm load zpm-zsh/fast-syntax-highlighting,async
zpm load zsh-users/zsh-autosuggestions,async
zpm load jeffreytse/zsh-vi-mode,async


echo "zpm loaded!"

# zplug "zsh-users/zsh-autosuggestions"
# zplug "jeffreytse/zsh-vi-mode"
# Install plugins if there are plugins that have not been installed
# if ! zplug check --verbose; then
#     printf "Install? [y/N]: "
#     if read -q; then
#         echo; zplug install
#     fi
# fi

# Then, source plugins and add commands to $PATH
# zplug load --verbose
